In [5]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import spacy
import re
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
bbc_data = pd.read_csv("bbc_news.csv")
bbc_data.head()

,Unnamed: 0,index,title,pubDate,guid,link,description
0,0,6684,Can I refuse to work?,"Wed, 10 Aug 2022 15:46:18 GMT",https://www.bbc.co.uk/news/business-62147992,https://www.bbc.co.uk/news/business-62147992?a...,With much of the UK enduring another period of...
1,1,9267,'Liz Truss the Brief?' World reacts to UK poli...,"Mon, 17 Oct 2022 11:35:12 GMT",https://www.bbc.co.uk/news/world-63285480,https://www.bbc.co.uk/news/world-63285480?at_m...,The UK's political chaos has been watched arou...
2,2,7387,Rationing energy is nothing new for off-grid c...,"Wed, 31 Aug 2022 05:20:18 GMT",https://www.bbc.co.uk/news/uk-scotland-highlan...,https://www.bbc.co.uk/news/uk-scotland-highlan...,Scoraig in the north west Highlands has long h...
3,3,767,The hunt for superyachts of sanctioned Russian...,"Tue, 22 Mar 2022 14:37:01 GMT",https://www.bbc.co.uk/news/60739336,https://www.bbc.co.uk/news/60739336?at_medium=...,"Wealthy Russians sanctioned by the US, EU and ..."
4,4,3712,Platinum Jubilee: 70 years of the Queen in 70 ...,"Wed, 01 Jun 2022 23:17:33 GMT",https://www.bbc.co.uk/news/uk-61660128,https://www.bbc.co.uk/news/uk-61660128?at_medi...,A quick look back at the Queen's 70 years on t...

In [7]:
bbc_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   1000 non-null   int64
 1   index        1000 non-null   int64
 2   title        1000 non-null   str
 3   pubDate      1000 non-null   str
 4   guid         1000 non-null   str
 5   link         1000 non-null   str
 6   description  1000 non-null   str
dtypes: int64(2), str(5)
memory usage: 371.3 KB

In [8]:
title=pd.DataFrame(bbc_data['title'])
title.head()

                                               title
0                              Can I refuse to work?
1  'Liz Truss the Brief?' World reacts to UK poli...
2  Rationing energy is nothing new for off-grid c...
3  The hunt for superyachts of sanctioned Russian...
4  Platinum Jubilee: 70 years of the Queen in 70 ...

cleaning the data

In [10]:
#lowercase
title['lowercase']=title['title'].str.lower()
title.head()

,title,lowercase
0,can i refuse to work?,can i refuse to work?
1,'liz truss the brief?' world reacts to uk poli...,'liz truss the brief?' world reacts to uk poli...
2,rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...
3,the hunt for superyachts of sanctioned russian...,the hunt for superyachts of sanctioned russian...
4,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...

In [11]:
#stop word removal
en_stopwords = set(stopwords.words('english'))
title['stopword_removed'] = title['lowercase'].apply(lambda x: ' '.join([word for word in x.split() if word not in en_stopwords]))
title.head()

,title,lowercase,stopword_removed
0,can i refuse to work?,can i refuse to work?,refuse work?
1,'liz truss the brief?' world reacts to uk poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...
2,rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community
3,the hunt for superyachts of sanctioned russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs
4,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds

In [17]:
#punctuation removal
title['no_stopword_punct_removed'] = title['stopword_removed'].apply(lambda x: re.sub(r'[^\w\s]', '', x))
title.head()

,title,lowercase,stopword_removed,no_stopword_punct_removed
0,can i refuse to work?,can i refuse to work?,refuse work?,refuse work
1,'liz truss the brief?' world reacts to uk poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...,liz truss brief world reacts uk political turmoil
2,rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community,rationing energy nothing new offgrid community
3,the hunt for superyachts of sanctioned russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs,hunt superyachts sanctioned russian oligarchs
4,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds,platinum jubilee 70 years queen 70 seconds

In [ ]:
#tokenize
title['token_raw']=title.apply(lambda x:word_tokenize(x['no_stopword_punct_removed']),axis=1)
title['tokens_clean'] =title.apply(lambda x:word_tokenize(x['no_stopword_punct_removed']),axis=1)
title.head()

,title,lowercase,stopword_removed,no_stopword_punct_removed,token_raw,tokens_cleann
0,can i refuse to work?,can i refuse to work?,refuse work?,refuse work,"[refuse, work]","[refuse, work]"
1,'liz truss the brief?' world reacts to uk poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...,liz truss brief world reacts uk political turmoil,"[liz, truss, brief, world, reacts, uk, politic...","[liz, truss, brief, world, reacts, uk, politic..."
2,rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community,rationing energy nothing new offgrid community,"[rationing, energy, nothing, new, offgrid, com...","[rationing, energy, nothing, new, offgrid, com..."
3,the hunt for superyachts of sanctioned russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs,hunt superyachts sanctioned russian oligarchs,"[hunt, superyachts, sanctioned, russian, oliga...","[hunt, superyachts, sanctioned, russian, oliga..."
4,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds,platinum jubilee 70 years queen 70 seconds,"[platinum, jubilee, 70, years, queen, 70, seco...","[platinum, jubilee, 70, years, queen, 70, seco..."

In [21]:
#lemmatizing
lemmatizer = WordNetLemmatizer()
title['token_clean_lemmatized'] = title['tokens_cleann'].apply(lambda x: [lemmatizer.lemmatize(word) for word in x])
title.head()

,title,lowercase,stopword_removed,no_stopword_punct_removed,token_raw,tokens_cleann,token_clean_lemmatized
0,can i refuse to work?,can i refuse to work?,refuse work?,refuse work,"[refuse, work]","[refuse, work]","[refuse, work]"
1,'liz truss the brief?' world reacts to uk poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...,liz truss brief world reacts uk political turmoil,"[liz, truss, brief, world, reacts, uk, politic...","[liz, truss, brief, world, reacts, uk, politic...","[liz, truss, brief, world, reacts, uk, politic..."
2,rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community,rationing energy nothing new offgrid community,"[rationing, energy, nothing, new, offgrid, com...","[rationing, energy, nothing, new, offgrid, com...","[rationing, energy, nothing, new, offgrid, com..."
3,the hunt for superyachts of sanctioned russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs,hunt superyachts sanctioned russian oligarchs,"[hunt, superyachts, sanctioned, russian, oliga...","[hunt, superyachts, sanctioned, russian, oliga...","[hunt, superyachts, sanctioned, russian, oliga..."
4,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds,platinum jubilee 70 years queen 70 seconds,"[platinum, jubilee, 70, years, queen, 70, seco...","[platinum, jubilee, 70, years, queen, 70, seco...","[platinum, jubilee, 70, year, queen, 70, second]"

In [ ]:
token_raw_list =sum(title['token_raw'],[])
tokens_clean_list =sum(title['token_clean_lemmatized'],[])

post tagging

In [27]:
nlp =spacy.load('en_core_web_sm')

In [28]:
spacy_doc =nlp(' '.join(tokens_clean_list))

In [31]:
pos_df=pd.DataFrame(columns=['token','pos_tag'])
for token in spacy_doc:
    pos_df =pd.concat([pos_df,pd.DataFrame.from_records({'token':[token.text],'pos_tag':[token.pos_]})],ignore_index=True)

In [32]:
pos_df_count = pos_df.groupby(['token','pos_tag']).size().reset_index(name='counts').sort_values(by='counts',ascending=False)
pos_df_count.head(10)

        token pos_tag  counts
30       2022     NUM      47
1162  england   PROPN      45
870       cup   PROPN      39
3056      say    VERB      37
3707       uk   PROPN      37
3840      war    NOUN      34
2386      new     ADJ      31
3948    world    NOUN      30
3949    world   PROPN      26
3710  ukraine   PROPN      23

In [33]:
verbs =pos_df_count[pos_df_count.pos_tag=='VERB'][0:10]
verbs

        token pos_tag  counts
3056      say    VERB      37
3711  ukraine    VERB      22
358      beat    VERB      13
2133     make    VERB      13
3461     take    VERB      13
1651      hit    VERB      13
1459      get    VERB      13
1380    found    VERB      13
1473     give    VERB      11
3918      win    VERB      10

In [34]:
adj=pos_df_count[pos_df_count.pos_tag=='ADJ'][0:10 ]
adj

        token pos_tag  counts
2386      new     ADJ      31
3010  russian     ADJ      22
403       big     ADJ      12
1324    first     ADJ      12
1306    final     ADJ      11
2478     open     ADJ      11
1955     last     ADJ      10
3097   second     ADJ       8
2394     next     ADJ       8
3978    young     ADJ       7

NER

In [36]:
ner_df =pd.DataFrame(columns=['token','ner_tag'])
for ent in spacy_doc.ents:
    ner_df =pd.concat([ner_df,pd.DataFrame.from_records({'token':[ent.text],'ner_tag':[ent.label_]})],ignore_index=True)

In [37]:
ner_df.head()

       token   ner_tag
0    russian      NORP
1    70 year      DATE
2  70 second      TIME
3       bull       ORG
4          1  CARDINAL

In [38]:
ner_df_count = ner_df.groupby(['token','ner_tag']).size().reset_index(name='counts').sort_values(by='counts',ascending=False)
ner_df_count.head(10)

       token   ner_tag  counts
34      2022  CARDINAL      30
451  russian      NORP      25
223    first   ORDINAL      15
35      2022      DATE      11
450   russia       GPE      10
233   france       GPE      10
339   london       GPE       9
519     tory      NORP       9
531       uk       GPE       8
409      one  CARDINAL       8